### ISSUE TITLE
Federated timeline の和訳について

### ISSUE THREAD

**Issue by pinfort** [pinfort/mastodon#5]
現状「連邦タイムライン」ですが、
連合の方がいい、そのままでいいなど多様な意見が散見されます。
このissueで話し合いましょう。

**Comment by lindwurm** [comment]
Mastodonが "A GNU Social-compatible" を謳っているので、GNU SocialのUIプラグインとしてよく用いられる[Qvitter](https://git.gnu.io/h2p/Qvitter)の訳を確認したところ、ここでは **連合** が用いられています。

> マイクロブロガー`連合`は道徳と団結を大切にして、中央集権化された資本主義なサービスからの離脱を目指しています。
> 
>`連合`: {site-title}上のアカウントが無くても{site-title}のユーザーをフォローしたり、そのユーザーからフォローされたり、そのユーザーと交流できるという意味で私たちは **「連合」(\"Federation\")**
 を成しています。StatusNetまたはGNU socialのいかなるサーバー、もしくは[Ostatus](http://www.w3.org/community/ostatus/wiki/Main_Page)プロトコルをベースにしたいかなるサービスでもいいのでユーザー登録すれば、この「連合」に参加できます! また、誰かに提供されているサーバーやサービスに参加する必要はないのです…このすばらしい[GNU social](http://www.gnu.org/software/social/)ソフトウェアを自分のサーバーにインストールしてもいいんです! :)

ref: https://git.gnu.io/h2p/Qvitter/blob/9b7aa477ab55dc5d558148d4342f4eff2279e354/locale/ja.json#L101

**Comment by jg1uaa** [comment]
お邪魔します。
「連系」というのはどうでしょうか。
電力系の用語ですが、Mastodonという系(system)が連なっている、というのを意識したいので。
ご検討ください。

**Comment by lindwurm** [comment]
わたしも`instance`の訳は少し気になりました。他にも `favourite` が `いいね` だったり `お気に入り` だったりと安定しないので、対語表的なものが欲しいところです

**Comment by pinfort** [comment]
サーバーに関してはそっちほうが一般の人にはわかりやすいのかなと思ったので現状そうしていますが、まずいようでしたら変えます
お気に入りの訳が安定していないのは完全に私のミスです　お気に入りに統一しようと思いますがいかがでしょう？

**Comment by jg1uaa** [comment]
確かにサーバーは理解しやすいですし、マズくないです。
しかし、インスタンスという語が他サービスとMastodonとの違いを示しているのではないかと考え、
コメントしました。

Favouritesについては、自分も「お気に入り」の方が良いと思うのですが、
Twitter/Facebookでは「いいね」になっているのを見るに、
こちらに合わせた方が移行組にとって違和感なく受け容れられるのではないでしょうか。

**Comment by lindwurm** [comment]
サーバーのほうが伝わりやすいというのと、日本語訳がmergeされる前から使っていたひとは原文からそのままインスタンスで理解しているというのがあって、どのへんで折り合いをつけるかはなかなか難しそうな気がします。

Favouritesは「お気に入り」で賛成です。原文とアイコンを尊重すべきかと。

**Comment by pinfort** [comment]
favoritesはとりあえずお気に入りの方向でいきます。

**Comment by NeetShin** [comment]
はじめまして。
> >> Twitter/Facebookでは「いいね」になっているのを見るに、
> こちらに合わせた方が移行組にとって違和感なく受け容れられるのではないでしょうか。
この件については同意です。しかし現状、TwitterやFacebookなどのSNSで「いいね」が用いられているのは_Like_の日本語訳であり、_Favorite_の日本語訳では無いのはご存知でしょうか。
開発者様が敢えて_Like_では無い_Favorite_を採用したのであれば、我々も「お気に入り」で統一すべきかと思われます。

また、話がずれてしまっていますが、Federatedは_連合_, instanceは_インスタンス_が現状多くの日本人ユーザーの間で用いられているようなので、そちらを推奨したいです。

**Comment by kotarok** [comment]
Federated → 連合
Instance → インスタンス
Favourite → お気に入り

僕もこの案に賛成です。「連邦」は「邦」の字の国家という意味が明らかにコンテキストに合っていない過剰な意味を含んでいますし、余計な意味を含まない「連合」で妥当かと思います。

「インスタンス」「お気に入り」に関しては、別の訳語だともとの言葉の意味からずれてしまいます。現状のコンテキストだけを考えれば別の案でも問題なく見えるケースも、サービスが進化する内にコンテキストがずれる可能性があります。現状への過剰最適や言語の意味を超えた過剰翻訳は避けたほうが、特にまだ始まったばかりのサービスに於いては良いと思います。

**Comment by jg1uaa** [comment]
なんか日本国内の急激なMastodonの広がりで、連邦/サーバで定着しつつあるような気がします…
修正するのはもう遅い段階になってたりしませんか？

**Comment by lindwurm** [comment]
報告が遅れました。

このIssue内では

* Federated: 連合
* Instance: インスタンス
* Favourite: お気に入り

で概ね同意が取れており、（リセット前の mstdn.jp でのやりとりで）これらに統一してPRを投げるという話が出ていたので、

* 「お気に入り」への統一: https://github.com/tootsuite/mastodon/pull/1623 (merged at https://github.com/tootsuite/mastodon/commit/38e24a699b65ba5e397709a3a7d1681da02b173f)
* 「連合」および「インスタンス」への統一: https://github.com/tootsuite/mastodon/pull/1631 (merged at https://github.com/tootsuite/mastodon/commit/9966bd27c2f568b34dc6d6d428301120b2153182)

が各Pull Requestに含まれており、日本語ロケールが公式なリリースとして初めて含まれた [v1.1.2](https://github.com/tootsuite/mastodon/releases/tag/v1.1.2) では上の表記で統一された状態になっています。

素直に安定性を重視して `v1.1.1` から `v1.1.2` 以降へアップデートしている[*]インスタンスでは最初から「連合タイムライン」「インスタンス」「お気に入り」になっているはずで、当該Issueは解決したものと思われます。 cc/ @pinfort

[*] 現在では通常のインスタンス運用が目的の場合は `master` ブランチではなくリリースを使用することが推奨されています: https://github.com/tootsuite/mastodon#checking-out
